# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# added webhook

language: r
sudo: required
cache: packages
before_install:
  - sudo apt-get -y install libharfbuzz-dev
  - sudo apt-get -y install libfribidi-dev
addons:
  apt:
    update: true
before_cache: Rscript -e 'remotes::install_cran("textshaping");remotes::install_cran("pkgdown")'

matrix:
  include:
   - r: release
   - r: devel

deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github(ssh_id = Sys.getenv("TRAVIS_DEPLOY_KEY", ""))'
  skip_cleanup: true

warnings_are_errors: true
